### PR TITLE
Allow employees to perform File Uploads

### PR DESCRIPTION
**Pull request by L00162772**
Employees now have the ability to upload files, view files, and delete files. Can perform actions cfrom the edit employee screen and view actions from the View Employee screen
Screenshot 2021-07-15 at 09 44 43
Screenshot 2021-07-15 at 09 45 01
Screenshot 2021-07-15 at 09 45 08
Screenshot 2021-07-15 at 09 45 24

### CODE REVIEW

**Review by JoseSunoj — APPROVED** [review]
Great work Damien. Approved.

**Review by 97047619 — APPROVED** [review]
Approved

**Review by johnreethu — APPROVED** [review]
This change will meet the acceptance criteria for uploading the images by the user.

**Review by L00163105 — APPROVED** [review]
Cool :)

**Pull request merged**
