### PR TITLE
Code to manage deploying the terraform infrastructure with GitHub actions

### PR DESCRIPTION
**Pull request by L00162772**

### CODE REVIEW

**Review by JoseSunoj — COMMENTED** [review]
Hi Damien,
Great Job, you did it well. Please review tear-down-infrastructure.yml, line number- 32, if it is Terraform Destroy, then it will be more apt in my opinion. Otherwise all good.
Thank you for your effort.

**Review by JoseSunoj — APPROVED** [review]
Thanks Damien.

**Comment by L00162772** [comment]
> Hi Damien,
> Great Job, you did it well. Please review tear-down-infrastructure.yml, line number- 32, if it is Terraform Destroy, then it will be more apt in my opinion. Otherwise all good.
> Thank you for your effort.

This is now done @JoseSunoj

**Review by 97047619 — APPROVED** [review]
Looks good

**Pull request merged**
