### PR TITLE
PR to merge changes for generating the javadoc into the main develop branch

### PR DESCRIPTION
**Pull request by L00162772**
Classes updated to include javadoc comments where they were missing
Some javadoc can be improved but this PR ensures the javadoc step runs successfully
Steps for generating javadoc locally 
Screenshot 2021-07-21 at 17 29 41
are found here - https://github.com/rlennon/smallwindow21/wiki/Generate-Javadoc-Locally

### CODE REVIEW

**Review by JoseSunoj — APPROVED** [review]
Approved. Thank you.

**Review by 97047619 — APPROVED** [review]
Approved

**Review by johnreethu — COMMENTED** [review]
Well done!

**Review by L00163105 — APPROVED** [review]
Looks good :)

**Pull request merged**
